DoAnASP/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineStoreBUS.BUS;
namespace DoAnASP.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/
        public ActionResult Main()
        {
            return View(ProducerBUS.List());
            // Quan Ly Menu hang San Xuat
        }
        public ActionResult LoaiSP()
        {
            return View(LoaiSPBUS.List());
            // AAAAAAAAAA
        }
	}
}

DoAnASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Ustora Demo</title>

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/Access/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Access/css/font-awesome.min.css">

    <script src="~/Access/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Access/css/owl.carousel.css">
    <link rel="stylesheet" href="~/Access/style.css">
    <link rel="stylesheet" href="~/Access/css/responsive.css">
    <link rel="stylesheet" href="~/Access/css/login.css">
    <script src="~/Access/js/modernizr.js"></script>
    <link href="~/Access/Datetimepicker/css/bootstrap-datepicker3.css" rel="stylesheet" />
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />

    <link href="~/Access/css/jquery-ui.css" rel="stylesheet" />
</head>
<body>
    <header class="banner">
        <div class="header-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <nav class="user-menu">
                            @using Microsoft.AspNet.Identity
                            @using WineStoreConnection
                            @if (Request.IsAuthenticated)
                            {

                                var db = new WineStoreConnectionDB();
                                WineStoreConnection.AspNetUser user = db.SingleOrDefault<WineStoreConnection.AspNetUser>("Select * from AspNetUsers where Id=@0", User.Identity.GetUserId());

                                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <ul>
                                        <li><a href="@Url.Action("Profile","Account")"><i class="fa fa-user"></i> Hi,@user.Name</a></li>
                                        @if (User.IsInRole("Admin"))
                                        {

                                            <li><a href="/Admin"><i class="fa fa-user"></i> Quản trị </a></li>
                                        }
                                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Đăng xuất </a></li>


                                    </ul>


                                }



                            }
                            else
                            {

                                <ul>
                                    <li><a class="cd-signin" id="btnLoginButton" href="#"><i class="fa fa-user"></i> Đăng nhập </a></li>

                                    <li><a class="cd-signup" href="#0"><i class="fa fa-user"></i>Đăng Ký</a></li>
                                </ul>


                            }







                        </nav>
                    </div>
                </div>
            </div>
        </div> <!-- End header area -->
    </header>



    <div class="cd-user-modal">
        <!-- this is the entire modal form, including the background -->
        <div class="cd-user-modal-container">
            <!-- this is the container wrapper -->
            <ul class="cd-switcher">
                <li><a href="#0">Đăng nhập </a></li>
                <li><a href="#0">Đăng Ký </a></li>
            </ul>
            @Html.Action("Login", "Account")
            @Html.Action("Register", "Account")


            <div id="cd-reset-password">
                <!-- reset password form -->
                <p class="cd-form-message">Nhập email vào để chúng tôi gửi mật khẩu tới email của bạn !</p>

                <form class="cd-form">
                    <p class="fieldset">
                        <label class="image-replace cd-email" for="reset-email">E-mail</label>
                        <input class="full-width has-padding has-border" id="reset-email" type="email" placeholder="E-mail">
                        <span class="cd-error-message">Lỗi xảy ra ở đây </span>
                    </p>

                    <p class="fieldset">
                        <input class="full-width has-padding" name="" type="submit" value="Gửi ">
                    </p>
                </form>

                <p class="cd-form-bottom-message"><a href="#0">Trở lại trang đăng nhập </a></p>
            </div> <!-- cd-reset-password -->
            <a href="#0" class="cd-close-form">Close</a>
        </div> <!-- cd-user-modal-container -->
    </div> <!-- cd-user-modal -->


    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="logo">
                        <h1><a href="@Url.Action("Index","Home")"><img src="~/img/logo.png"></a></h1>
                    </div>
                </div>

                <div class="col-md-6">
                    <form action="@Url.Action("Search","Product")" name="frmsearch" method="GET">
                        <div id="custom-search-input">

                            <div class="input-group col-md-12">

                                <input name="txtSearch" id="txtSearch" type="text" class="form-control input-lg mySearch" placeholder="Nhập từ khoá tìm kiếm " />
                                <span class="input-group-btn">
                                    <button type="submit" id="btnSearch" name="btnSearch" class="btn btn-info btn-lg">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </span>


                            </div>

                        </div>
                    </form>

                </div>



                <div class="col-sm-3">
                    <div class="shopping-item">
                        <a href="@Url.Action("Index","Cart")">
                            Giỏ hàng   <i class="fa fa-shopping-cart"></i> <span class="product-count">

                                @{
                                    int Q = 0;
                                    var cart = Session["Cart"];
                                    var list = new List<DoAnASP.Models.CartItems>();
                                    if (cart != null)
                                    {

                                        list = (List<DoAnASP.Models.CartItems>)cart;
                                        foreach (var item in list)
                                        {

                                            Q = Q + item.Quantity;
                                        }
                                    }


                                } @Q
                            </span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div> <!-- End site branding area -->


    <div class=" mainmenu-area">

        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"> @Html.ActionLink("Trang chủ", "Index", "Home") </li>
                        @Html.Action("Main", "Menu")
                        @Html.Action("LoaiSP", "Menu")

                    </ul>



                </div>
            </div>
        </div>
    </div> <!-- End mainmenu area -->



    @RenderBody()

    <div class="footer-top-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <div class="footer-about-us">
                        <h2>u<span>Stora</span></h2>
                        <p>Shop bán rượu </p>
                        <div class="footer-social">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>






                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Thông tin  </h2>
                        <ul>
                            <li><a href="#">Tài khoản </a></li>
                            <li><a href="#">Giỏ hàng </a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-menu">
                        <h2 class="footer-wid-title">Loại Rượu </h2>
                        <ul>
                            <li><a href="#">BLENDED</a></li>
                            <li><a href="#">SCOTCH</a></li>
                            <li><a href="#">VANG</a></li>
                            <li><a href="#">BRANDY</a></li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6">
                    <div class="footer-newsletter">
                        <h2 class="footer-wid-title">Thông tin liên hệ </h2>
                        <p>Điện thoại tư vấn : 01652092560 - 3859293</p>

                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End footer top area -->
    <script src="~/Access/js/jquery.js"></script>

    <!-- Bootstrap JS form CDN -->
    <script src="~/Access/js/bootstrap.min.js"></script>
    <script src="~/Access/js/jquery-ui.js"></script>
    <!-- jQuery sticky menu -->
    <script src="~/Access/js/owl.carousel.min.js"></script>
    <script src="~/Access/js/jquery.sticky.js"></script>

    <!-- jQuery easing -->
    <script src="~/Access/js/jquery.easing.1.3.min.js"></script>

    <!-- Main Script -->
    <script src="~/Access/js/main.js"></script>

    <script src="~/Access/js/login.js"></script>

    <!-- Slider -->
    <script type="text/javascript" src="~/Access/js/bxslider.min.js"></script>

    <script type="text/javascript" src="~/Access/js/script.slider.js"></script>


    <script src="~/Access/bootstrap-touchspin/jquery.bootstrap-touchspin.js"></script>
    <script src="~/Access/Datetimepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>

    <script src="~/Access/js/Search.js"></script>
    <script src="~/Access/js/Comment.js"></script>

    <script>
        $('#txtQuantity').TouchSpin({
            min: 1
            //verticalButtons: true
        });
        $("input[id*='txtQuantity_']").TouchSpin({
            min: 1,
            verticalbuttons: false
        });
    </script>



    <script type="text/javascript">
        $('a[id*=btnAddToCart_]').on('click', function () {
            //var proId = $(this).attr('data-proid');
            var proId = $(this).data('proid');
            $('#txtProId').val(proId);

            $('#addToCart-form').submit();
        });

        $("#notification").hide();
        $("#message").hide();


    </script>
    <script src="~/Access/js/Account.js"></script>

    <script>
        $("input[id*='txtQuantity_']").TouchSpin({
            min: 1,
            verticalbuttons: true
        });


        $("#mssgerror").hide();



    </script>
    <script src="~/Access/js/AjaxCart.js"></script>

    @RenderSection("jsFooter", required: false)

</body>
</html>
<noembed>