DoAnASP/Areas/Admin/ViewModels/ProductViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WineStoreConnection;
using WineStoreBUS;

namespace Admin.ViewModel
{
    public class ProductViewModels : SanPham
    {
        [Display(Name = "Hình ảnh")]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase ImageUpLoad { get; set; }
        public HttpPostedFileBase ImageUpLoad0 { get; set; }
        public HttpPostedFileBase ImageUpLoad1 { get; set; }
    }
}

DoAnASP/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineStoreBUS.BUS;
using WineStoreConnection;
using System.Web.Script.Serialization;
using DoAnASP.Models;
using Microsoft.AspNet.Identity;
namespace DoAnASP.Controllers
{
    public class CommentsController : Controller
    {
        //
        // GET: /Comments/
        public ActionResult Index(int idproduct,int page)
        {
          

            PetaPoco.Page < Comment > ListComments = CommentsBUS.ListSearchFound(idproduct, page);
            ViewData["idProduct"] = idproduct;
            return View(ListComments);
        }

        [HttpPost]
        public JsonResult AddComment(string CommentModel)
        {

            var jsonCart = new JavaScriptSerializer().Deserialize<CommentModel>(CommentModel);


          
            Comment cm = new Comment();
            cm.IdProduct = jsonCart.IdProduct ;
            cm.IdUser = User.Identity.GetUserId();
            cm.UrlMedia = jsonCart.UploadMedia;
            cm.DateComment = DateTime.Now;
            cm.BiXoa = false;
            cm._Comment = jsonCart.Comments;

            CommentsBUS.Create(cm);
            return Json(new
            {
                status = true
            });

        }
	}
}

DoAnASP/Controllers/LoaiSPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineStoreBUS.BUS;
namespace DoAnASP.Controllers
{
    public class LoaiSPController : Controller
    {
        //
        // GET: /LoaiSP/
        public ActionResult Index(int id,int? page)
        {
            //Toan Bo Loai San Phamss
            if (page == null)
            {
                page = 1;
            }
            PetaPoco.Page<WineStoreConnection.SanPham> ds_SP = ProductBUS.ListByTypeForPage(id,page.Value);
            return View(ds_SP);
        }
	}
}

DoAnASP/Controllers/ProducerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineStoreBUS.BUS;

namespace DoAnASP.Controllers
{
    public class ProducerController : Controller
    {
        //
        // GET: /Producer/
        public ActionResult Index(int id,int? page)
        {
            //Toan bo producers
            if (page == null)
                page = 1;
            PetaPoco.Page<WineStoreConnection.SanPham> ds_SP = ProductBUS.ListByProducer(id,page.Value);
            return View(ds_SP);
        }
       

        public ActionResult AllProducer()
        {
            
            return View(ProducerBUS.List());
        }
        
	}
}

DoAnASP/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineStoreBUS.BUS;
namespace DoAnASP.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Detail(int id,int? page)
        {
            if(page == null)
            {

                page = 1;
            }
            WineStoreConnection.SanPham sp = ProductBUS.GetbyID(id);
            string a = ProducerBUS.NameProducerByID(sp.MaHangSanXuat);
            string b =  LoaiSPBUS.NameLoaiSPByID(sp.MaLoaiSanPham);
            ViewBag.HangSanXuat = a;
            ViewBag.LoaiSanPham =b;
            ViewData["page"] = page.Value;
           
          
            return View(sp);
        }
        public ActionResult Search(string txtSearch,int? page)
        {
            if (page== null)
            {

                page = 1;
            }
            var data = ProductBUS.ListSearchFound(txtSearch, page.Value);
            if (data.Items.Count == 1)
            {
                return Redirect(Url.Action("Detail", "Product", new { id = data.Items.First().MaSanPham }));
            }
            return View(data);
        }

        public JsonResult ListProduct(string q)
        {
            IEnumerable<WineStoreConnection.SanPham> data = ProductBUS.ListSearch(q);
            var name = data.Select(m => m.TenSanPham).ToList();
            var img = data.Select(m => m.HinhURL1).ToList();
            var id = data.Select(m => m.MaSanPham).ToList();

            var json = Json( new{
                data = name,
           
                status = true
                
            },JsonRequestBehavior.AllowGet);

           
            return json;
        }
        public ActionResult Top5ByProducer(int id)
        {

            return View(ProductBUS.ListTop5ByProducer(id));
        }
        public ActionResult Top5ByType(int id)
        {

            return View(ProductBUS.ListTop5ByType(id));
        }
      
	}
}

DoAnASP/Views/Product/Detail.cshtml
@model WineStoreConnection.SanPham


<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Shop</h2>
                </div>
            </div>
        </div>
    </div>
</div>
@if (@Model==null)
{
    <div class="single-product-area">
            <div class="zigzag-bottom"></div>
            <div class="container">
                <form id="addToCart-form" method="post" action="">
                    <input type="hidden" id="txtProId" name="txtProId" />
                </form>

             
                
                   
                    <div class="row">
                         <div class="col-md-12">
                                    <div class="alert alert-info" role="alert">Không Có sản phẩm nào  !</div>
                                    </div>
                        
                    </div>     
                    
                
            </div>
        </div>
}
else
{
    
    <div class="single-product-area">
    <div class="zigzag-bottom"></div>
    <div class="container">

        <div class="row">
            <div class="col-md-4">
                @Html.Action("Top5ByProducer", "Product", new { id = @Model.MaHangSanXuat})

            </div>
            <div class="col-md-8">
                <div class="product-content-right">
                    <div class="product-breadcroumb">
                        <a href="@Url.Action("Index","Home")">Trang chủ </a>
                        <a href="@Url.Action("Index", "LoaiSP", new { id = @Model.MaLoaiSanPham})">  @ViewBag.LoaiSanPham</a>
                        <a href="@Url.Action("Index", "Producer", new { id = @Model.MaHangSanXuat})"> @ViewBag.HangSanXuat</a>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="product-images">
                                <div class="product-main-img">
                                    <img src="~/@Model.HinhURL1" alt="">
                                </div>

                                <div class="product-gallery">
                                    <img src="~/@Model.HinhURL1" alt="">
                                    <img src="~/@Model.HinhURL2" alt="">
                                    <img src="~/@Model.HinhURL3" alt="">
                                </div>
                            </div>
                        </div>



                        <div class="col-sm-6">
                            <div class="product-inner">
                                <h2 class="product-name">@Model.TenSanPham</h2>
                                <div class="product-inner-price">
                                    @{ System.Globalization.CultureInfo cul = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }
                                    <ins> @Model.GiaSanPham.ToString("#,###", cul.NumberFormat) VNĐ</ins>
                                </div>
                                @using (Html.BeginForm("AddItemss", "Cart", FormMethod.Post, new { @class = "cart" }))
                                {
    
                                         <div class="quantity">

                                                        <input type="hidden" name="txtProIDCart" value="@Model.MaSanPham" >
                                                        <input type="number" class="" title="Qty" value="1" id="txtQuantity" name="txtQuantity" min="1" step="1">
                                         </div>
                                 
                                        
                                        <button class="add_to_cart_button" type="submit" name="btnAddToCart">Thêm vào giỏ </button>
                                    
                                   
                                     
                                }
                              
                                   
                           


                                <div class="product-inner-category">
                                    <p><i class="fa fa-eye"></i> :@Model.SoLuotXem   <i class="fa fa-shopping-cart"></i>: @Model.SoLuongBan  </p>

                                </div>
                                <div class="product-inner-category">
                                    <p>
                                        Thể loại : @ViewBag.LoaiSanPham <a href="">
                                        </a>. Xuất xứ: <a href="">@Model.XuatXu </a>,
                                        Hãng sản xuất :@ViewBag.HangSanXuat <a href=""></a>
                                    </p>
                                </div>

                                <div role="tabpanel">
                                    <ul class="product-tab" role="tablist">
                                        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Giới thiệu </a></li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="product-inner">
                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane fade in active" id="home">
                                        <h2>Giới thiệu </h2>
                                        <p>
                                            @Html.Raw(Model.MoTa)
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="col-md-12">

                            <div class="related-products-wrapper">
                                <h2 class="related-products-title">Sản phẩm cùng Loại </h2>
                                <div class="related-products-carousel">
                                    @Html.Action("Top5ByType", "Product", new { id = @Model.MaLoaiSanPham  })
                                </div>
                            </div>

                        </div>




                    </div>
                </div>

            </div>



        </div>
        @{
            
                  
                    int page = int.Parse(ViewData["page"].ToString());
        }
    
        @Html.Action("Index", "Comments", new { idproduct = Model.MaSanPham, page = page })
 
 
    
    
    </div>
    </div>
              
}

DoAnASP/Views/Product/Search.cshtml
@model PetaPoco.Page<WineStoreConnection.SanPham>

@{
    ViewBag.Title = "Search";
}

<div class="product-big-title-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="product-bit-title text-center">
                    <h2>Shop</h2>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Action("SearchBar", "Home");

@if (Model.Items.Count > 0)
{
    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <form id="addToCart-form" method="post" action="">
                <input type="hidden" id="txtProId" name="txtProId" />
            </form>




            <div class="row">

                @foreach (var item in Model.Items)
                {

                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="single-shop-product">
                            <div class="product-upper">
                                <img src="~/@item.HinhURL2" alt="@item.TenSanPham">
                            </div>
                            <h2><a href="@Url.Action("Detail", "Product", new { id=@item.MaSanPham}) ">@item.TenSanPham </a></h2>
                            <div class="product-carousel-price">
                                @{ System.Globalization.CultureInfo cul = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }
                                <ins> @item.GiaSanPham.ToString("#,###", cul.NumberFormat) VNĐ</ins>
                            </div>


                            <div class="product-option-shop">
                                <a class="add_to_cart_button" id="btnAddToCart_@item.MaSanPham" data-proid="@item.MaSanPham" href="#">Thêm vào giỏ</a>
                            </div>



                        </div>
                    </div>
                }








            </div>



            <div class="row">
                <div class="col-md-12">
                    <div class="product-pagination text-center">
                        <nav>
                            <ul class="pagination">



                                @for (int i = 1; i <= Model.TotalPages; i++)
                                {
                                    <li><a href="/Producer/Index/@Model.Items[i].MaHangSanXuat?page=@i">@i</a></li>

                                }





                            </ul>
                        </nav>
                    </div>
                </div>
            </div>




        </div>
    </div>

}
else
{
    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <form id="addToCart-form" method="post" action="">
                <input type="hidden" id="txtProId" name="txtProId" />
            </form>




            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-info" role="alert">Không Có sản phẩm nào  !</div>
                </div>

            </div>


        </div>
    </div>
}

DoAnASP/Views/Product/Top5ByProducer.cshtml
@model IEnumerable<WineStoreConnection.SanPham>
@{
    Layout = null;
}

<div class="single-sidebar">
    <h2 class="sidebar-title">Sản phẩm cùng Hãng </h2>
    @foreach (var item in Model)
    {
         <div class="thubmnail-recent">
        <img src="~/@item.HinhURL2" class="recent-thumb" alt="">
        <h2>@Html.ActionLink(@item.TenSanPham, "Detail", "Product", new { id = @item.MaSanPham }, null)</h2>
        <div class="product-sidebar-price">
            @{ System.Globalization.CultureInfo cul = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }
            <ins> @item.GiaSanPham.ToString("#,###", cul.NumberFormat) VNĐ</ins>
           
        </div>
     </div>
        
    }
   



</div>

DoAnASP/Views/Product/Top5ByType.cshtml
@model IEnumerable<WineStoreConnection.SanPham>
@{
    Layout = null;
}
@foreach (var item in Model)
{
    
    <div class="single-product">
    <div class="product-f-image">
        <img src="~/@item.HinhURL1" alt="">
        <div class="product-hover">
            <a href="@Url.Action("AddItems", "Cart", new { Proid=@item.MaSanPham,quantity=1 })" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i> Thêm vào giỏ </a>
            @Html.ActionLink("Xem Chi Tiết ", "Detail", "Product", new { id = item.MaSanPham }, new { @class = "view-details-link" })
            
        </div>
    </div>

    <h2>@Html.ActionLink(@item.TenSanPham, "Detail", "Product", new { id = item.MaSanPham }, new { @class = "view-details-link" }) </h2>

    <div class="product-carousel-price">

        @{ System.Globalization.CultureInfo cul = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }
    <ins> @item.GiaSanPham.ToString("#,###", cul.NumberFormat) VNĐ</ins>

    </div>
</div>
}