DoAnASP/Areas/Admin/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineStoreBUS.BUS;
using WineStoreConnection;
using Microsoft.AspNet.Identity;
namespace DoAnASP.Areas.Admin.Controllers
{
     [Authorize(Roles = "Admin")]
    public class AspNetUsersController : Controller
    {
        //
        // GET: /Admin/AspNetUsers/
        public ActionResult Index()
        {
           // QUan ly tai khoan 
        
            IEnumerable<AspNetUser> data = AccountBUS.ListAccount();
            return View(data);
        }
        public ActionResult Edit(string id)
        {
            AspNetUser user = AccountBUS.LoadUserById(id);

            return View(user);
        }
        [HttpPost]
        public ActionResult Edit(AspNetUser user,FormCollection form)
        {
            AspNetUser u = AccountBUS.LoadUserById(user.Id);
         

              if(AccountBUS.CheckAccoutByEmail(user) == true)
                    {

                        ViewBag.ThongBao = 2;
                        return View(u);

                    }
                    else
                    {
                        u.UserName = user.Email;
                        u.Email = user.Email;
                        u.Name = user.Name;
                        u.Phone = user.Phone;
                        u.Address = user.Address;
                        if (user.Id != User.Identity.GetUserId())
                        {
                            u.BiXoa = user.BiXoa;
                        }
                        AccountBUS.Update(u);
                        ViewBag.ThongBao = 1;
                    }
            
              if (user.Id != User.Identity.GetUserId())
              {

                  //

                  bool admin = false;
                  if (form["chkAdmin"] != null)
                  {
                      admin = true;
                  }

                  if (admin)
                  {
                      if (!AccountBUS.CheckRoles(user))
                      {
                          AspNetUserRole uroles = new AspNetUserRole();
                          uroles.RoleId = AccountBUS.LoadIdRolesAdmin();
                          uroles.UserId = user.Id;
                          AccountBUS.UploadRolesAdmin(uroles);
                          ViewBag.ThongBao = 1;

                      }

                  }
                  else
                  {
                      if (AccountBUS.CheckRoles(user))
                      {
                          AspNetUserRole uroles = new AspNetUserRole();
                          uroles.RoleId = AccountBUS.LoadIdRolesAdmin();
                          uroles.UserId = user.Id;
                          AccountBUS.DelRoles(uroles);
                          ViewBag.ThongBao = 1;

                      }

                  }
              }
              else
              {

                  ViewBag.ThongBao = 3;
                  return View(u);
              }

            return View(u);
        }
	}
}

DoAnASP/Areas/Admin/Views/AspNetUsers/Edit.cshtml
@model WineStoreConnection.AspNetUser
@{
    ViewBag.Title = "Edit";
}


@{
    ViewBag.Title = "Create";
}


      

@using (Html.BeginForm("Edit", "AspNetUsers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    
    <div id="content">
        <div class="panel box-shadow-none content-header">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3 class="animated fadeInLeft">ADMIN</h3>
                    <p class="animated fadeInDown">
                        <a href="@Url.Action("Index","AspNetUsers")">QL Tài khoản  </a> <span class="fa-angle-right fa"></span> Sửa
                    </p>
                </div>
            </div>
        </div>
        <div class="form-element">
            <div class="col-md-12 padding-0">
                <div class="col-md-8">
                    <div class="panel form-element-padding">
                        <div class="panel-heading">
                            <h4>Sửa sản phẩm</h4>
                        </div>
                        <div class="col-md-12">
                        @if (ViewBag.ThongBao != null)
                        {
                            if (ViewBag.ThongBao == 1)
                            {
                                <div class="col-md-6 col-md-offset-3">
                                    <div class="alert alert-success" role="alert">Cập nhật  thành công </div>
                                </div>
                            } else if(ViewBag.ThongBao ==2)
                            {
                                <div class="col-md-6 col-md-offset-3">
                                    <div class="alert alert-warning" role="alert">Email Đã tồn tại không được thêm email này </div>
                                </div>
                                
                            }
                            else
                            {
                                <div class="col-md-6 col-md-offset-3">
                                    <div class="alert alert-danger" role="alert"> Cập nhật thông tin thành công và Bạn không được phép thay đổi quyền của mình  </div>
                                </div>
                                
                            }
                           
                        }
                        </div>
                        <div class="panel-body" style="padding-bottom:30px;">

                            <div class="form-group" hidden="hidden">
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.Id, new { @class = "form-control" })</div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label text-right">Email </label>
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.Email, new { @class = "form-control",type = "Email" })</div>
                             
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label text-right">Họ Tên </label>
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.Name, new { @class = "form-control" })</div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label text-right">Địa chỉ </label>
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.Address, new { @class = "form-control" })</div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label text-right">Số điện thoại</label>
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.Phone, new { @class = "form-control"}) </div>
                               
                            </div>
                                             
                            <div class="form-group">
                                <label class="col-sm-2 control-label text-right">Bị xóa</label>
                                <div class="col-sm-10">
                                    <div class="form-group form-animate-checkbox">
                                        @Html.CheckBoxFor(model => model.BiXoa, new { @class = "checkbox" })
                                    </div>
                                </div>
                            </div>
                            @if (WineStoreBUS.BUS.AccountBUS.CheckRoles(Model))
                            {    <div class="form-group">
                                <label class="col-sm-2 control-label text-right">Admin</label>
                                <div class="col-sm-10">
                                    <div class="form-group form-animate-checkbox">
                                       <input id="chkAdmin" name="chkAdmin" type="checkbox" class="checkbox" value="true" checked>
                                    </div>
                                </div>
                            </div>
                                
                            }
                            else
                            {
                                
                                 <div class="form-group">
                                <label class="col-sm-2 control-label text-right">Admin</label>
                                <div class="col-sm-10">
                                    <div class="form-group form-animate-checkbox">
                                        <input id="chkAdmin" name="chkAdmin"  type="checkbox" class="checkbox" value="true">
                                    </div>
                                </div>
                            </div>
                            }
                            
                           
                            <div class="form-group">
                                <label class="col-sm-2 control-label text-right"></label>
                                <div class="col-sm-10" style="margin-top:10px;"><input id="btnChange" value="Lưu" type="submit" class="btn btn-primary" /></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

DoAnASP/Areas/Admin/Views/AspNetUsers/Index.cshtml
@using WineStoreConnection;
@model IEnumerable<AspNetUser>
@{
    ViewBag.Title = "Index";
}
<div id="content">
    <div class="panel box-shadow-none content-header">
        <div class="panel-body">
            <div class="col-md-12">
                <h3 class="animated fadeInLeft">ADMIN</h3>
                <p class="animated fadeInDown">
                    <a href="~/Admin/AspNetUsers">QL Tài khoản </a> <span class="fa-angle-right fa"></span> Danh Sách Tài khoản 
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-12 top-20 padding-0">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading"><h3><a href="~/Admin/AspNetUsers">Danh sách tài khoản</a></h3> </div>
                <div class="panel-body">

                    <div class="responsive-table">
                        <table id="datatables-example" class="table table-striped table-bordered" style="width:100%;" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Email</th>
                                    <th>Họ Tên </th>
                                    <th>Địa chỉ </th>
                                    <th>Số Điện Thoại</th>
                                    <th>Quyền </th>
                                    <td>Bị xóa</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.ActionLink(item.Id, "Edit", new { id = item.Id }) </td>
                                       
                                        <td>@Html.DisplayFor(s => item.Email)</td>
                                        <td>@Html.ValueFor(s => item.Name)</td>
                                        <td>@Html.DisplayFor(s => item.Address)</td>
                                        <td>@Html.DisplayFor(s => item.Phone   )</td>
                                        @if (WineStoreBUS.BUS.AccountBUS.CheckRoles(item))
                                        {
                                            <td> Admin </td>
                                        }
                                        else
                                        {

                                            <td>Khách Hàng </td>
                                        }
                                        <td>
                                            <div class="form-group form-animate-checkbox">
                                                @Html.CheckBoxFor(s => item.BiXoa, new { @class = "checkbox", disabled = "" })
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>