DoAnASP/Areas/Admin/Controllers/TypeOfProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineStoreBUS;
using WineStoreConnection;
using WineStoreBUS.BUS;

namespace DoAnASP.Areas.Admin.Controllers
{
    [Authorize(Roles="Admin")]
    public class TypeOfProductAdminController : Controller
    {
        //
        // GET: /Admin/TypeOfProductAdmin/
        public ActionResult Index()
        {
            var db = new WineStoreConnectionDB();
            IEnumerable<LoaiSanPham> dslsp = db.Query<LoaiSanPham>("Select * from LoaiSanPham");
            return View(dslsp);
        }

        // GET: LoaiSP/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LoaiSP/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiSP/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham collection)
        {
            LoaiSPBUS.Create(collection);
            return RedirectToAction("Index");
        }

        // GET: LoaiSP/Edit/5
        public ActionResult Edit(int id)
        {
            var db = new WineStoreConnectionDB();
            LoaiSanPham lsp = db.SingleOrDefault<LoaiSanPham>("Select * from loaisanpham l where maloaisanpham = " + id);
            return View(lsp);
        }

        // POST: LoaiSP/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LoaiSP/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoaiSP/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Save(LoaiSanPham collection)
        {
            LoaiSPBUS.Update(collection);
            return RedirectToAction("Index");
        }
	}
}

DoAnASP/Areas/Admin/Views/TypeOfProductAdmin/Create.cshtml
@model WineStoreConnection.LoaiSanPham


@using (Html.BeginForm("Create", "TypeOfProductAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div id="content">
        <div class="panel box-shadow-none content-header">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3 class="animated fadeInLeft">ADMIN   </h3>
                    <p class="animated fadeInDown">
                        <a href="~/Admin/TypeOfProductAdmin">QL Loại Sản Phẩm</a> <span class="fa-angle-right fa"></span> Thêm
                    </p>
                </div> 
            </div>
        </div>
        <div class="form-element">
            <div class="col-md-12 padding-0">
                <div class="col-md-8">
                    <div class="panel form-element-padding">
                        <div class="panel-heading">
                            <h4>Thêm loại sản phẩm mới</h4>
                        </div>
                        <div class="panel-body" style="padding-bottom:30px;">
                                                        
                            <div class="form-group">
                                 <label class="col-sm-2 control-label text-right" style="margin-top:8px">Tên loại SP</label>
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.TenLoaiSanPham, new { @class = "form-control" })</div>
                            </div>                           

                            <div class="form-group">
                                 <label class="col-sm-2 control-label text-right" style="margin-top:8px"></label>
                                <div class="col-sm-10" style="margin-top:10px;"><input value="Thêm" type="submit" class="btn btn-primary" /></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<!-- end: content -->

DoAnASP/Areas/Admin/Views/TypeOfProductAdmin/Edit.cshtml
@model WineStoreConnection.LoaiSanPham

@using (Html.BeginForm("Save", "TypeOfProductAdmin", FormMethod.Post))
{
    <div id="content">
        <div class="panel box-shadow-none content-header">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3 class="animated fadeInLeft">ADMIN</h3>
                    <p class="animated fadeInDown">
                        <a href="~/Admin/TypeOfProductAdmin">QL Loại Sản Phẩm</a><span class="fa-angle-right fa"></span> Sửa
                    </p>
                </div>
            </div>
        </div>
        <div class="form-element">
            <div class="col-md-12 padding-0">
                <div class="col-md-8">
                    <div class="panel form-element-padding">
                        <div class="panel-heading">
                            <h4>Sửa loại sản phẩm</h4>
                        </div>
                        <div class="panel-body" style="padding-bottom:30px;">

                            <div class="form-group" hidden="hidden">
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.MaLoaiSanPham, new { @class = "form-control" })</div>
                            </div>
                            <div class="form-group">
                                 <label class="col-sm-2 control-label text-right" style="margin-top:8px">Tên loại SP</label>
                                <div class="col-sm-10">@Html.TextBoxFor(model => model.TenLoaiSanPham, new { @class = "form-control" })</div>
                            </div>
                            <div class="form-group">
                                 <label class="col-sm-2 control-label text-right" style="margin-top:8px">Bị xóa</label>
                                <div class="col-sm-10">
                                    <div class="form-group form-animate-checkbox">
                                       @Html.CheckBoxFor(model => model.BiXoa, new { @class = "checkbox" })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                 <label class="col-sm-2 control-label text-right" style="margin-top:8px"></label>
                                <div class="col-sm-10"><input value="Lưu" type="submit" class="btn btn-primary" /></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<!-- end: content -->

DoAnASP/Areas/Admin/Views/TypeOfProductAdmin/Index.cshtml
@model IEnumerable<WineStoreConnection.LoaiSanPham>
<!-- start: content -->
<!-- start: Content -->
<div id="content">
    <div class="panel box-shadow-none content-header">
        <div class="panel-body">
            <div class="col-md-12">
                <h3 class="animated fadeInLeft">ADMIN</h3>
                <p class="animated fadeInDown">
                    <a href="~/Admin/TypeOfProductAdmin">QL Loại Sản Phẩm</a><span class="fa-angle-right fa"></span>Danh Sách LSP
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-12 top-20 padding-0">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading"><h3>@Html.ActionLink("Thêm", "Create")</h3></div>
                <div class="panel-body">
                    <div class="responsive-table">
                        <table id="datatables-example" class="table table-striped table-bordered" style="width:100%;" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Tên</th>
                                    <th>Bị xóa</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.ActionLink(item.TenLoaiSanPham, "Edit", new { id = item.MaLoaiSanPham }) </td>
                                        <td>
                                            <div class="form-group form-animate-checkbox">
                                                @Html.CheckBoxFor(m => item.BiXoa, new { @class = "checkbox", disabled = "" })
                                            </div>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end: content -->